# File: build.yaml
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          string_interpolation: braces
          enum_name: AppLocale
          translate_var: t
          maps:
            - countries
