# File: build.yaml
targets:
  $default:
    builders:
      fast_i18n:
        options:
          string_interpolation: braces

          enum_name: DynamicFormAppLocale
          translate_var: dynamicFormTranslation
          output_file_name: dynamic_form_localizations.g.dart
          maps:
            - countries
