import '../model/dynamic_form_models.dart';

class AutoCalculateField extends Field {
  AutoCalculateField({
    required String fieldId,
    required FieldTypes? fieldType,
    required String label,
    bool required = false,
    bool readOnly = false,
    String? labelId,
    bool? maskText,
    int? maxLength,
    String? inputType,
    List<Option>? options,
    String? confirmField,
    bool? strict,
    String? fieldName,
    int? versionId,
    CompositeValue? value,
    List<DependsOnValue>? dependsOn,
    List<Field>? children,
    bool? isCapitalized,
    String? validationExpression,
    String? validationErrorMessage,
    CompareDate? compareDate,
    int? parentId,
  }) : super(
          fieldName: fieldName,
          versionId: versionId,
          fieldId: fieldId,
          required: required,
          readOnly: readOnly,
          label: label,
          labelId: labelId,
          maskText: maskText,
          maxLength: maxLength,
          inputType: inputType,
          options: options,
          isCapitalized: isCapitalized,
          fieldType: fieldType,
          strict: strict,
          confirmField: confirmField,
          dependsOn: dependsOn,
          value: value,
          parentId: parentId,
          children: children,
          compareDate: compareDate,
          validationExpression: validationExpression,
          validationErrorMessage: validationErrorMessage,
        );
}
